# Generated by Django 4.1.3 on 2022-12-27 19:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nombre"),
                ),
                ("image", models.ImageField(max_length=255, upload_to=None)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        max_length=200,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nombre"),
                ),
                ("cover_image", models.ImageField(max_length=255, upload_to=None)),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1200, verbose_name="Descripción"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        max_length=200,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Título"),
                ),
                (
                    "extract",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Extracto"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=1200, verbose_name="Contenido"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        max_length=255, upload_to=None, verbose_name="Imagen de portada"
                    ),
                ),
                (
                    "content_image",
                    models.ImageField(
                        max_length=255,
                        upload_to=None,
                        verbose_name="Imagen de contenido",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default=None,
                        editable=False,
                        max_length=200,
                        null=True,
                        populate_from="title",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.author",
                        verbose_name="Autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="news.category",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Noticia",
                "verbose_name_plural": "Noticias",
            },
        ),
    ]
