# Generated by Django 4.1.3 on 2022-12-27 17:37

from django.db import migrations
from news.models import Author
import autoslug.fields


def add_authors(apps, schema_editor):

    authors = [
        {
            "name": "Thanos",
            "image": "https://drive.google.com/uc?export=view&id=1RWpzNFLva4Gz3W6yi2uyDhryqi4kUPS_",
            "is_active": True,
        },
        {
            "name": "Otto",
            "image": "https://drive.google.com/uc?export=view&id=1xaMwDQGfjgpw6lEuE7fMDhwbGIu-riW1",
            "is_active": True,
        },
        {
            "name": "Leo",
            "image": "https://drive.google.com/uc?export=view&id=1NIPXRpfvoiQeh0L9hY7BT5ghFiVo-KOu",
            "is_active": True,
        },
    ]

    for author in authors:
        new_author = Author(
            name=author["name"], image=author["image"], is_active=author["is_active"]
        )
        new_author.save()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_authors)]
