# Generated by Django 4.1.3 on 2022-12-27 17:37

from django.db import migrations
from news.models import Category
import autoslug.fields


def add_categories(apps, schema_editor):

    categories = [
        {
            "name": "Premier League",
            "cover_image": "https://drive.google.com/uc?export=view&id=1Hh2JlhZqbc--T7-GaETl4UJrD2OTwHRY",
            "description": "Ligra profesional de fútbol jugada en Inglaterra.",
            "is_active": True,
        },
        {
            "name": "La Liga",
            "cover_image": "https://drive.google.com/uc?export=view&id=117nP6Irpl2qfXQZ8Ue51iMHH5k0NoolA",
            "description": "Ligra profesional de fútbol jugada en España.",
            "is_active": True,
        },
        {
            "name": "Serie A",
            "cover_image": "https://drive.google.com/uc?export=view&id=1cLkFS6uY8vdKU6pQs8CLT2KVEST44duz",
            "description": "Ligra profesional de fútbol jugada en Italia.",
            "is_active": True,
        },
        {
            "name": "Bundesliga",
            "cover_image": "https://drive.google.com/uc?export=view&id=1um5g88Mv7cIIqkd1pJZgfdBKybkNOhw5",
            "description": "Ligra profesional de fútbol jugada en Alemania.",
            "is_active": True,
        },
        {
            "name": "Ligue 1",
            "cover_image": "https://drive.google.com/uc?export=view&id=18G4J627qDlbH4-G8wvC0GxS8FzNPD7bL",
            "description": "Ligra profesional de fútbol jugada en Francia.",
            "is_active": True,
        },
        {
            "name": "Liga Betplay",
            "cover_image": "https://drive.google.com/uc?export=view&id=12lKMvvz3UaeDXydCZJQUTPF3VRyL1v7K",
            "description": "Ligra profesional de fútbol jugada en Colombia.",
            "is_active": True,
        },
    ]

    for category in categories:
        new_category = Category(
            name=category["name"],
            cover_image=category["cover_image"],
            description=category["description"],
            is_active=category["is_active"],
        )
        new_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_auto_20221227_1737"),
    ]

    operations = [migrations.RunPython(add_categories)]
