# Generated by Django 4.1.3 on 2022-12-27 19:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_auto_20221227_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                max_length=200,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                max_length=200,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                max_length=200,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
